### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Krocko** [adriancable/homebridge-nest-native#1]
Hi Adrian. Thank you for your work on this plugin.
If i use the username from the Nest app i get the following error:
```
Jul 17 18:00:14 raspberrypi homebridge[5445]: [NestNative] Auth failed which likely means the username/password is not valid. Check you are using the same username/password as the Nest app
Jul 17 18:00:14 raspberrypi homebridge[5445]: [NestNative] Error: nest_auth_failed
Jul 17 18:00:14 raspberrypi homebridge[5445]:     at /usr/local/lib/node_modules/homebridge-nest-native/lib/nest-connection.js:47:36
Jul 17 18:00:14 raspberrypi homebridge[5445]:     at tryCatcher (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
Jul 17 18:00:14 raspberrypi homebridge[5445]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
Jul 17 18:00:14 raspberrypi homebridge[5445]:     at Promise._settlePromiseAt (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
Jul 17 18:00:14 raspberrypi homebridge[5445]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
Jul 17 18:00:14 raspberrypi homebridge[5445]:     at Async._drainQueue (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
Jul 17 18:00:14 raspberrypi homebridge[5445]:     at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
Jul 17 18:00:14 raspberrypi homebridge[5445]:     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
Jul 17 18:00:14 raspberrypi homebridge[5445]:     at processImmediate (internal/timers.js:439:21)
```
But password and username are right.

If i use my Nest E-Mail as username i got the following error:
```
Jul 17 18:06:30 raspberrypi homebridge[9490]: Nest_API_error TypeError: Cannot convert undefined or null to object
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at Function.keys (<anonymous>)
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at Connection.<anonymous> (/usr/local/lib/node_modules/homebridge-nest-native/lib/nest-connection.js:79:36)
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at tryCatcher (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at Promise._settlePromiseAt (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at Async._drainQueue (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-nest-native/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
Jul 17 18:06:30 raspberrypi homebridge[9490]:     at processImmediate (internal/timers.js:439:21)
```

**Comment by adriancable** [comment]
Can you go to home.nest.com on your PC and log in using your U&P there? Also, please check that you have 2-step verification (2FA) disabled in Settings/Account Security on home.nest.com.

**Comment by Krocko** [comment]
Thank you for your answer.
I can log in with email and password on the website. 
2FA is disabled.

**Comment by KozzakO** [comment]
I am getting the following error:

[2019-7-17 17:44:24] [NestNative] Error: Accessories must be created with a non-empty displayName.
    at NestThermostatAccessory.Accessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:49:27)
    at NestThermostatAccessory.NestDeviceAccessory (/home/pi/homebridge-nest-native-master/lib/nest-device-accessory.js:59:13)
    at new NestThermostatAccessory (/home/pi/homebridge-nest-native-master/lib/nest-thermostat-accessory.js:36:23)
    at NestPlatform.<anonymous> (/home/pi/homebridge-nest-native-master/index.js:224:29)
    at NestPlatform.<anonymous> (/home/pi/homebridge-nest-native-master/index.js:230:7)
    at /home/pi/homebridge-nest-native-master/index.js:255:32
    at tryCatcher (/home/pi/homebridge-nest-native-master/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/homebridge-nest-native-master/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/pi/homebridge-nest-native-master/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/pi/homebridge-nest-native-master/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/pi/homebridge-nest-native-master/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/pi/homebridge-nest-native-master/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/homebridge-nest-native-master/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/homebridge-nest-native-master/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/pi/homebridge-nest-native-master/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Any ideas?

**Comment by adriancable** [comment]
I made some changes to give more meaningful errors if 2FA is enabled, and also set a default name for the thermostat if it isn't defined in the Nest account. Please pull from the repository and try again. Thanks for all your help!

**Comment by adriancable** [comment]
Oops, just re-read what you wrote. Problem seems to be because you have no thermostats. Let me look into it and I'll have a fix for you in a bit

**Comment by KozzakO** [comment]
It works now!!! Would be awesome if you could also add humidity. Thank you so much for the great plugin!

**Comment by adriancable** [comment]
Great - glad it works. I have already added humidity for the themostat. I didn't know the Protect has a humidity sensor - does it?

**Comment by adriancable** [comment]
Krocko - can you please replace nest-connection.js in your homebridge-nest-native/lib directory with the attached file (you will need to rename the extension from .txt to .js)? Use your Nest email address as your login. Then restart homebridge. You'll get a whole load of debug info - please copy and paste and email that to me at adrian.cable@gmail.com and I'll try to figure out what is happening. Thanks!

[nest-connection.txt](https://github.com/adriancable/homebridge-nest-native/files/3403343/nest-connection.txt)

**Comment by adriancable** [comment]
Krocko - actually I have just found a bug which may have been causing your issue. (I wasn't handling the case where there were only Protects and no thermostats.) Please pull from the repository and try again, and let me know if this has fixed it for you.

**Comment by Krocko** [comment]
Now i have the devices (i have 3 protect) in the home app. But i don‘t know wich device is wich.

**Comment by Krocko** [comment]
Ok i got it. I must add a "Label" for each protect in the nest app.  It is working now.

**Comment by adriancable** [comment]
Great! Glad it's working for you.

**Comment by KozzakO** [comment]
> Great - glad it works. I have already added humidity for the themostat. I didn't know the Protect has a humidity sensor - does it?

@adriancable I was thinking more of a separate icon for humidity. Otherwise the humidity reading is a little buried in the thermostat settings. But this is only a minor issue.
