### ISSUE TITLE
Unable to find the NPM package

### ISSUE THREAD

**Issue by ashunshah** [adriancable/homebridge-nest-native#2]
I am getting a 404. Is the package published? I did a search too couldn't find it

**Comment by Krocko** [comment]
It is not on npm right now. 
Install it with `sudo chown -R $USER /usr/local && npm install -g https://github.com/adriancable/homebridge-nest-native`

**Comment by ashunshah** [comment]
Great! That worked thanks! Do you want to close the issue or keep it open for others?

**Comment by adriancable** [comment]
I'll close it. I will probably "take over" the original homebridge-nest package soon, so don't want to publish a new package just yet.
